- .github/workflows/binder.yaml
I discovered this a few hours ago, I was going to suggest making this cleanup and using it as an example for binderhub but now you've posted it on https://github.com/machine-learning-apps/repo2docker-action/issues/25#issuecomment-649616185 😀.
> Remove unnecessary checkout in binder button action

- create_docker_image.sh
Hopefully fixes https://discourse.jupyter.org/t/how-to-build-mybinder-image-automatically-at-each-commit/538 with a bit of [bash magic](https://stackoverflow.com/a/2264537)
> If no INPUT_IMAGE_NAME then ensure repo name is lowercase

- README.md
- action.yml
- create_docker_image.sh
This PR adds a new input named `REPO_DIR` for setting [--target-repo-dir](https://repo2docker.readthedocs.io/en/latest/usage.html?highlight=target-repo-dir#cmdoption-jupyter-repo2docker-target-repo-dir) option when running `repo2docker`.
Personally, I needed this to let my image have separate `REPO_DIR` and `HOME` for customization and easier mounting of persistent user volume to home directory. Hope this make sense and also help others. By default, it's set to `/home/${NB_USER}` following the current behavior, so shouldn't give any impact on existing uses.
> Add `REPO_DIR` input for setting `--target-repo-dir` option

- README.md
I wanted to provide detailed instructions for getting user images
to non-dockerhub repositoroes, given the aggressive rate limits
dockerhub now has[1], and the (now redacted) plan to purge older
images[2].
[1]: https://docs.docker.com/docker-hub/download-rate-limit/
[2]: https://www.docker.com/blog/scaling-dockers-business-to-serve-millions-more-developers-storage/
> Add detailed quay.io instructions

- README.md
This PR updates the `repo2docker` logo image location so that it's properly rendered in the README. In particular the new link points to the `jupyterhub` GitHub org and updates to the latest `repo2docker` commit hash (just updating `jupyter` -> `jupyterhub` didn't seem to work -- I'm not sure why)
> Update repo2docker logo image URL

- bootstrap.sh
In particular, this will error with an informative
message when DOCKER_USERNAME and DOCKER_PASSWORD is not
set
> Enable better error handling in ./bootstrap.sh

- Dockerfile
trigger_binder.sh is already marked with +x on the filesystem,
so does not need this extra line in the Dockerfile
> Remove redundant chmod of trigger_binder.sh

- .github/workflows/test.yaml
- README.md
- action.yml
- create_docker_image.sh
Closes #74 by reverting a change in #73 and making sure that the behavior that was undocumented now is documented.
I consider this fix quite critical to fix because we have no release system so I assume many use `@master`, which will make their use of this action break.
> fix regression that makes DOCKER_UESRNAME required sometimes

- Dockerfile
It came to my attention that repo2docker-action has been stuck with an old version ([2021.03.0-70.g43891a6](https://hub.docker.com/layers/jupyter/repo2docker/2021.03.0-70.g43891a6/images/sha256-b17d42ae1526c56c21e2d969c65b0ca367664310a2e68e197384e04070c60e51)) of repo2docker since mid-July. Seems like upstream has decided to migrate to Quay.io leaving Docker Hub: jupyterhub/repo2docker#1076
> Use repo2docker image from Quay.io

- .github/workflows/release-updates.yaml
- RELEASE.md
This PR aligns this repository that contains a GitHub action definition with some practices for the other repositories in the jupyterhub org that also defines GitHub actions.
With this in place and a new release made, we can also update the readme to suggest referencing `@v1` or similar rather than `@master`.
> Add release automation and documentation

- create_docker_image.sh
Earlier, we were only setting it if we pushed the image
> Set output image name unconditionally

- create_docker_image.sh
docker push has a couple of advantages over --push in
repo2docker:
- If we use --push, we can not actually run the docker image-tests/
before pushing! So if an image-test/ fails, the docker image is still
pushed! This is very confusing behavior.
- It times out sometimes, causing issues where the image just
fails to push after building. docker push doesn't have this
issue - see https://github.com/2i2c-org/utoronto-image/issues/20,
where we had to manually run a docker push.
- docker push provides more useful output than --push
This commit also removes some code duplication - we now build
the image regardless, and use the flag just to differentiate pushing.
An unused bash function was also deleted.
> Use docker push to push image

- create_docker_image.sh
Address Git security issue that causes Docker builds to suddenly fail. 
See https://github.com/jupyterhub/repo2docker-action/issues/89#issue-1203976137 and https://github.com/actions/checkout/issues/760
> Add Github workspace as safe directory on commit local Dockerfile for Binder cache

- Dockerfile
Reverts jupyterhub/repo2docker-action#93
Seems to have broken it for some people - reverting until I can investigate some more.
> Revert "Remove python install step in Dockerfile"

- README.md
- action.yml
- create_docker_image.sh
Acts as a useful 'escape hatch' for specifying any repo2docker params we don't already have a parameter for.
> Add input to pass extra arguments to repo2docker

- create_docker_image.sh
repo2docker triest to set these labels automatically, but because we call repo2docker on the local checkout, it doesn't know where the build is coming from.
If you look at a built image, right now you get:
`skopeo --override-os linux inspect  docker://quay.io/2i2c/cloudbank-data8-image:aa7e0df7adf4`
```
"Labels": {
...
"repo2docker.ref": "",
"repo2docker.repo": "local",
"repo2docker.version": "2022.10.0+169.g6250c06"
},
```
This makes it difficult to trace the built image back to a repo.
We just explicitly set those here.
> Specify repo and ref as a docker label

- Dockerfile
Brings in a fix for https://github.com/docker/docker-py/issues/3240, until docker-py is released upstream.
Ref https://github.com/jupyterhub/repo2docker-action/issues/117
EDIT: fixes #117
EDIT: closes #119
> Avoid version of docker-py with a regression

- .github/draft_workflows/chatops.yaml
- README.md
- action_files/create_deployment.py
- trigger_binder.sh
This is the first step to renaming from master to main, approve and I'll get the rest done.
> Update master branch references to main where suitable

- create_docker_image.sh
> Docker run tests defined in `image-tests` as root user

- create_docker_image.sh
Reverts jupyterhub/repo2docker-action#111
Based on discussion in https://github.com/jupyterhub/repo2docker-action/pull/111#issuecomment-2127719200
> Revert "Docker run tests defined in `image-tests` as root user"

- README.md
> Add warning for image-tests when using DockerFile
